### ISSUE TITLE
Stream chunk object to opencv

### ISSUE THREAD

**Issue by thoithoi58** [bitstuffing/tplink-tapo#1]
Hi, I was wandering around and found your project. I am thinking about streaming the video directly rather than saving it to a file. However I cant find any solution to do this, can you suggest any idea?

**Comment by bitstuffing** [comment]
Hi @thoithoi58 , 

In the past I was thinking about this, remember that there is no documentation about TAPO API and all is reversed engineered. There is a limitation, when you reach aprox. 10MB of video streaming the video connection is reset, so you need a "server implementation" in the middle. But... said that, if you want to invest or implement it, you will have some problems to overcome:

- (for remote implementation, internet connection) The streaming is not open, I mean... you have to open an stream connection (https), send a JSON body, and this response could be your video, or other command (move to the left, restart...). 
- (for local network implementation) Your kind of develop could be implemented, enabling this option in the client APP, or implementing this functionality in local.py.

My implemenation is different because I don't "hack" the camera, I implement a python client for the official API. Probably you're seeking something like https://github.com/hacefresko/CVE-2021-4045-PoC implementation to exploit and gain root access to the device to enable this functionality in the operative system.

I hope this answer may shed some light in your question.

(EDIT) Inside root tests.sh script, the last line is the "local" client implementation (with an screenshot) of your request with ffmpeg

**Comment by thoithoi58** [comment]
Hi @bitstuffing 

That was a really fast response, thanks for that!

My question seems to not clear enough, so I'm gonna explain again what I want to do:

-  In the `writeVideo` method, I saw you wrote a `chunk` variable to a file (in this case a mp4 video) locally. Instead of waiting for the file done being written, I want to capture it frame by frame and show up in maybe OpenCV or Pillow. I've tried to convert the `chunk` (bytes type) to an image but it seem to be just a small pieces of a frame.

-  Secondly, is there any way to overcome  aprox. 10MB of video or approx 2 minutes of video. Because in the mobile app, the limit is up to 5 minutes.

Thanks

**Comment by bitstuffing** [comment]
I will try to answer you:

- Yes, the `chunk` variable is the packet with the response that interested me, but the current implementation is that the request receive two kind of responses: the video chunk or a string with a JSON, similar to a single API consumption but embed or wrapped in this SSL connection. That is the situation, and that is the reason for that implementation. If you want a "_window_" or direct frame visualization you need your "_custom_" implementation, and I suggest change f (pipe open to the default file) to a server, Pillow or a simple video player call with a pipe, but... sorry, I think it's not directly related with the "sample library". For this reason my suggestion is use mplayer (that was my implementation in tests) in a bash script, and now (in production) this method implementation is used to store video in a FS like a CCAM in a cron. For me it's ok and enough.
- About 10 MB aprox of video, or the _issue_ of 2 minutes of video in app, well... I don't have any idea if _a fix_ could be implemented. I could see in the past the video size (when I was testing) is not always in the 100% of requests the same, and the API request is not always respecting the "HD" resolution petition, sometimes it sends a SD video packet, but... it's the magic of reverse engineering. If TAPO could open his API it will be more clean but... at this moment all done is reverse engineering magic, not a official petition to an official open API. 

Just to close the dialog because I know that it's a feature request, not an issue... to offer you a "solution" for your request (you're able to fork it and implement that), this it's not a tested code (currently I'm not in front of a PC with the library to test & implement it, but if it could throw some light in your petition...):
```
import cv2 

cap = cv2.VideoCapture("video.mp4")
while(True):
     ret, frame = cap.read()
     cv2.imshow('frame',frame)
     if cv2.waitKey(1) & 0xFF == ord('q'):
          break
cap.release()
cv2.destroyAllWindows()
```

Greetings
